In [16]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/disease_prediction_synthetic_6000_rows.csv")
df = data.copy()
df

,Age,Gender,Fever,Fatigue,Blood_Glucose_mg_dL,WBC_Count_cells_uL,Platelet_Count_cells_uL,Disease
0,19,Female,1,1,86.2,3095,88800,Dengue
1,47,Male,0,1,144.8,3902,292860,Viral Infection
2,27,Female,0,1,103.1,8661,281170,Anemia
3,8,Male,1,1,61.9,3985,90155,Dengue
4,33,Male,0,0,74.6,7548,271762,Healthy
...,...,...,...,...,...,...,...,...
5995,40,Female,0,0,141.5,6079,255765,Diabetes
5996,40,Female,1,1,106.2,3400,298263,Viral Infection
5997,42,Male,1,1,77.3,4322,82161,Dengue
5998,8,Male,0,1,103.8,5725,217410,Anemia
5999,45,Male,1,1,97.9,4204,79161,Dengue

In [18]:
df['Gender_code'] = df['Gender'].astype('category').cat.codes
df['Disease_code'] = df['Disease'].astype('category').cat.codes

In [19]:
df['Disease'].value_counts()

Disease
Viral Infection    1460
Healthy            1360
Diabetes           1198
Dengue             1044
Anemia              938
Name: count, dtype: int64

In [20]:
df['Disease_code'].value_counts()

Disease_code
4    1460
3    1360
2    1198
1    1044
0     938
Name: count, dtype: int64

In [21]:
df

,Age,Gender,Fever,Fatigue,Blood_Glucose_mg_dL,WBC_Count_cells_uL,Platelet_Count_cells_uL,Disease,Gender_code,Disease_code
0,19,Female,1,1,86.2,3095,88800,Dengue,0,1
1,47,Male,0,1,144.8,3902,292860,Viral Infection,1,4
2,27,Female,0,1,103.1,8661,281170,Anemia,0,0
3,8,Male,1,1,61.9,3985,90155,Dengue,1,1
4,33,Male,0,0,74.6,7548,271762,Healthy,1,3
...,...,...,...,...,...,...,...,...,...,...
5995,40,Female,0,0,141.5,6079,255765,Diabetes,0,2
5996,40,Female,1,1,106.2,3400,298263,Viral Infection,0,4
5997,42,Male,1,1,77.3,4322,82161,Dengue,1,1
5998,8,Male,0,1,103.8,5725,217410,Anemia,1,0
5999,45,Male,1,1,97.9,4204,79161,Dengue,1,1

In [22]:
features = df.drop(['Disease_code', 'Disease', 'Gender'], axis=1)
target = df['Disease_code']

In [23]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(features, target, random_state=42)

In [46]:
from sklearn.linear_model import LogisticRegression

log_clf = LogisticRegression(max_iter=49)
log_clf.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=49)

In [25]:
from sklearn.ensemble import RandomForestClassifier

rfor_clf = RandomForestClassifier(n_estimators=42, n_jobs=3)
rfor_clf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=42, n_jobs=3)

In [45]:
from sklearn import svm
svm_clf = svm.SVC(kernel='linear', C=1.0)
svm_clf.fit(x_train_scaled, y_train)

SVC(kernel='linear')

In [44]:
from sklearn.preprocessing import StandardScaler

stf = StandardScaler()

x_train_scaled = stf.fit_transform(x_train)
x_test_scaled = stf.fit_transform(x_test)

In [27]:
from xgboost import XGBClassifier

xgb_clf = XGBClassifier(n_estimators=100, max_depth=6, random_state=42)
xgb_clf.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [47]:
rfor_preds = rfor_clf.predict(x_test)
svm_preds = svm_clf.predict(x_test_scaled)
log_preds = log_clf.predict(x_test_scaled)
xgb_preds = xgb_clf.predict(x_test)

In [29]:
from sklearn.metrics import accuracy_score, precision_score , recall_score, f1_score, confusion_matrix

In [39]:
from numpy import average
# for random forest model

print("Accuracy score: ", accuracy_score(rfor_preds, y_test))
print("precision score: ", precision_score(rfor_preds, y_test, average="macro"))
print("recall score: ", recall_score(rfor_preds, y_test, average="macro"))
print("f1 score: ", f1_score(rfor_preds, y_test, average="macro"))

Accuracy score:  0.804
precision score:  0.8036121998277848
recall score:  0.8033796362587902
f1 score:  0.8032767284796447

In [48]:
# for svm model

print("Accuracy score: ", accuracy_score(svm_preds, y_test))
print("precision score: ", precision_score(svm_preds, y_test, average="macro"))
print("recall score: ", recall_score(svm_preds, y_test, average="macro"))
print("f1 score: ", f1_score(svm_preds, y_test, average="macro"))

Accuracy score:  0.8213333333333334
precision score:  0.8219547427323171
recall score:  0.8206875226555184
f1 score:  0.8207728179701419

In [49]:
#for logistic regression

print("Accuracy score: ", accuracy_score(log_preds, y_test))
print("precision score: ", precision_score(log_preds, y_test, average="macro"))
print("recall score: ", recall_score(log_preds, y_test, average="macro"))
print("f1 score: ", f1_score(log_preds, y_test, average="macro"))

Accuracy score:  0.816
precision score:  0.8142610573615949
recall score:  0.8146384321419371
f1 score:  0.814354583561015

In [50]:
#for xboost classifer


print("Accuracy score: ", accuracy_score(xgb_preds, y_test))
print("precision score: ", precision_score(xgb_preds, y_test, average="macro"))
print("recall score: ", recall_score(xgb_preds, y_test, average="macro"))
print("f1 score: ", f1_score(xgb_preds, y_test, average="macro"))

Accuracy score:  0.7966666666666666
precision score:  0.7947980585420727
recall score:  0.79570969837862
f1 score:  0.7951913405512302